### ISSUE TITLE
Pattern copy-webpack-plugin 'FROM' 

### ISSUE THREAD

**Issue by krbaio3** [webpack-contrib/copy-webpack-plugin#139]
Hi!,

I have a question about the plugin. I'm using your plugin, and in my case, I need to load the files using a regex. I have been reviewing the documentation and it is not clear to me. I am not able to make it work because it gives me an error that 'the pattern must be an array'. I attach my code and error that gives me

Webpack:
```
new CopyWebpackPlugin({
      from: [/task_modules\/bk-module-\w+-?\w+\/dist\/((?!node_modules|bower_components).)*.(js|css|html)$/],
      to: './dist/tasks/[name]/[name].[ext]',
    }),
```

Error

```
Error: [copy-webpack-plugin] patterns must be an array
    at new CopyWebpackPlugin (C:\Users\user\Documents\cancel-webpack\node_modules\copy-webpack-plugin\dist\index.js:26:15)
    at Object.<anonymous> (C:\Users\user\Documents\cancel-webpack\webpack.config.js:168:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (C:\Users\user\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:96:18)
    at C:\Users\user\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:109:17
    at Array.forEach (native)
    at module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:107:15)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:153:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

Thanks!!

**Comment by JamesNimlos** [comment]
@krbaio3 not sure if you solved this, but check out the example. `[patterns]` is in brackets because it needs to be an array of objects, not because it's optional. Change your code to:
```javascript
new CopyWebpackPlugin([{
    from: /task_modules\/bk-module-\w+-?\w+\/dist\/((?!node_modules|bower_components).)*.(js|css|html)$/,
    to: './dist/tasks/[name]/[name].[ext]',
}])
```
I agree, the error potentially ambiguous since I ran into the same thing, but I ended up finding the answer in the example.

**Comment by Oliboy50** [comment]
@JamesNimlos I can't use a RegExp like you do in your `from` example

I end up with this error message:
```shell
ERROR in Path must be a string. Received /\/my-file.ext/
```
