### ISSUE TITLE
Cannot find module 'bluebird'

### ISSUE THREAD

**Issue by wbern** [webpack-contrib/copy-webpack-plugin#157]
```
module.js:487
    throw err;
    ^

Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\qvazzleer\Repos\Swegon%20Designer%20Suite\src\Swegon.Hera.Application\node_modules\copy-webpack-plugin\dist\index.js:3:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

My project is using `whatwg-fetch`, not `bluebird`.

**Comment by michael-ciniawsky** [comment]
Could you clean the npm cache, delete lockfile and install afresh and verify if this still happens  ?

**Comment by wbern** [comment]
Hi @michael-ciniawsky.

This did it for me. `rm -r -f .cache-loader package-lock.json node_modules/.cache`

I don't have a package-lock.json file so it must had been one of the cache sources (cache-loader and babel-loader's `cacheDirectory` option)
