### ISSUE TITLE
Issue after upgrading to webpack 4

### ISSUE THREAD

**Issue by danshmidt77** [webpack-contrib/copy-webpack-plugin#246]
Did someone came across the following issue after upgrading to webpack 4:

(node:15464) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at Object.apply (C:\workspace\ProovFE_V2\node_modules\webpack-plugin-copy\dist\index.js:76:14)
    at webpack (C:\workspace\ProovFE_V2\node_modules\webpack\lib\webpack.js:37:12)
    at processOptions (C:\workspace\ProovFE_V2\node_modules\webpack-cli\bin\webpack.js:436:16)
    at yargs.parse (C:\workspace\ProovFE_V2\node_modules\webpack-cli\bin\webpack.js:510:3)
    at Object.parse (C:\workspace\ProovFE_V2\node_modules\webpack-cli\node_modules\yargs\yargs.js:543:18)
    at C:\workspace\ProovFE_V2\node_modules\webpack-cli\bin\webpack.js:217:8
    at Object.<anonymous> (C:\workspace\ProovFE_V2\node_modules\webpack-cli\bin\webpack.js:512:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\workspace\ProovFE_V2\node_modules\webpack\bin\webpack.js:12:2)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

I have the recent     "webpack-plugin-copy": "^1.0.1"

**Comment by evilebottnawi** [comment]
@danshmidt77 `webpack-plugin-copy` is other plugin, we are `copy-webpack-plugin`, please create issue in repo `webpack-plugin-copy` or migrate on official webpack plugin (on `copy-webpack-plugin`). Thanks!

**Comment by danshmidt77** [comment]
Sorry :)
