### ISSUE TITLE
What versions of Webpack does the plugin support?

### ISSUE THREAD

**Issue by dyosick** [webpack-contrib/copy-webpack-plugin#273]
Hi
With webpack version 4.15.1 I got a building error:
```
D:\PATH_TO_MY_PROJECT\node_modules\copy-webpack-plugin\dist\index.js:186
                    trackedDirs.push(context);
                                ^

TypeError: trackedDirs.push is not a function
    at D:\PATH_TO_MY_PROJECT\node_modules\copy-webpack-plugin\dist\index.js:186:33
    at arrayEach (D:\PATH_TO_MY_PROJECT\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (D:\PATH_TO_MY_PROJECT\node_modules\lodash\lodash.js:9342:14)
    at D:\PATH_TO_MY_PROJECT\node_modules\copy-webpack-plugin\dist\index.js:184:30
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\PATH_TO_MY_PROJECT\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\PATH_TO_MY_PROJECT\node_modules\tapable\lib\Hook.js:35:21)
    at asyncLib.forEach.err (D:\PATH_TO_MY_PROJECT\node_modules\webpack\lib\Compiler.js:355:27)
    at done (D:\PATH_TO_MY_PROJECT\node_modules\neo-async\async.js:2854:11)
    at D:\PATH_TO_MY_PROJECT\node_modules\neo-async\async.js:2805:7
    at D:\PATH_TO_MY_PROJECT\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by evilebottnawi** [comment]
@dyosick `webpack@3` and `webpack@4`
