### ISSUE TITLE
TypeError: Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by koukimetal** [webpack-contrib/copy-webpack-plugin#312]
I created a small sample project using this plugin but I got this error. Does anyone have same issue?
Project: https://github.com/koukimetal/copy-webpack-plugin-sample
keitak@keita:~/IdeaProjects/copy-webpack-plugin-sample$ node --version
v9.11.2
keitak@keita:~/IdeaProjects/copy-webpack-plugin-sample$ npm --version
5.6.0
keitak@keita:~/IdeaProjects/copy-webpack-plugin-sample$ npm run build

> copy-webpack-plugin-sample@1.0.0 build /home/keitak/IdeaProjects/copy-webpack-plugin-sample
> webpack

/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/copy-webpack-plugin/dist/index.js:66
            context = compiler.options.context;
                                       ^

TypeError: Cannot read property 'context' of undefined
    at Object.apply (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/copy-webpack-plugin/dist/index.js:66:40)
    at plugins.forEach.plugin (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/enhanced-resolve/lib/ResolverFactory.js:276:10)
    at Array.forEach (<anonymous>)
    at Object.exports.createResolver (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/enhanced-resolve/lib/ResolverFactory.js:275:10)
    at ResolverFactory._create (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/ResolverFactory.js:60:28)
    at ResolverFactory.get (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/ResolverFactory.js:52:28)
    at NormalModuleFactory.getResolver (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/NormalModuleFactory.js:519:31)
    at /home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/NormalModuleFactory.js:165:32
    at /home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/NormalModuleFactory.js:129:4
    at hooks.beforeResolve.callAsync (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/NormalModuleFactory.js:396:5)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/tapable/lib/Hook.js:154:20)
    at NormalModuleFactory.create (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/NormalModuleFactory.js:377:28)
    at semaphore.acquire (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/Compilation.js:966:18)
    at Semaphore.acquire (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/util/Semaphore.js:29:4)
    at Compilation._addModuleChain (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/Compilation.js:965:18)
    at Compilation.addEntry (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/Compilation.js:1072:8)
    at compiler.hooks.make.tapAsync (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/SingleEntryPlugin.js:46:17)
    at AsyncParallelHook.eval [as callAsync] (eval at create (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncParallelHook.lazyCompileHook (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeCompile.callAsync.err (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/Compiler.js:545:20)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/Compiler.js:538:28)
    at readRecords.err (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/Compiler.js:278:11)
    at Compiler.readRecords (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/Compiler.js:405:11)
    at hooks.run.callAsync.err (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/Compiler.js:275:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeRun.callAsync.err (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/Compiler.js:272:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.run (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack/lib/Compiler.js:269:24)
    at processOptions (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack-cli/bin/cli.js:495:20)
    at yargs.parse (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/webpack-cli/bin/cli.js:498:3)
    at Object.parse (/home/keitak/IdeaProjects/copy-webpack-plugin-sample/node_modules/yargs/yargs.js:567:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! copy-webpack-plugin-sample@1.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the copy-webpack-plugin-sample@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/keitak/.npm/_logs/2019-01-12T06_03_05_975Z-debug.log
keitak@keita:~/IdeaProjects/copy-webpack-plugin-sample$

**Comment by evilebottnawi** [comment]
Feel free to investigate

**Comment by evilebottnawi** [comment]
Invalid usage:
```
module.exports = {
    resolve: {
        plugins: [
            new CopyWebpackPlugin([{ from: 'tmp/a.txt', to: 'dist/' }]),
        ]
    }
};
```

to

```
module.exports = {
        plugins: [
            new CopyWebpackPlugin([{ from: 'tmp/a.txt', to: 'dist/' }]),
        ]
};
```
