### ISSUE TITLE
[BUG] CopyPlugin not initializing - API schema mismatch

### ISSUE THREAD

**Issue by unm4sk1g** [webpack-contrib/copy-webpack-plugin#500]
- Operating System: Windows 10 Pro x64 build 18362
- Node Version: v12.18.0
- NPM Version: 6.14.5
- webpack Version: 4.15.1
- copy-webpack-plugin Version: 6.0.2

### Expected Behavior

Expecting plugin to copy modules without issues.

### Actual Behavior

```ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, toType?, force?, flatten?, transform?, cacheTransform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
    at validate (C:\Users\unm4sk\project\node_modules\copy-webpack-plugin\node_modules\schema-utils\dist\validate.js:96:11)
    at new CopyPlugin (C:\Users\unm4sk\project\node_modules\copy-webpack-plugin\dist\index.js:24:30)```
```
### Code

```
let copyPatterns = [
	{
		from: 'node_modules/node-raspberrypi-usbboot/blobs',
		to: 'modules/node-raspberrypi-usbboot/blobs',
	},
];

if (os.platform() === 'win32') {
	copyPatterns.push({
		from: `node_modules/lzma-native/${LZMA_BINDINGS_FOLDER}/liblzma.dll`,
		to: `modules/lzma-native/${LZMA_BINDINGS_FOLDER}/liblzma.dll`,
	});
}

module.exports = {
  ...
    plugins: [
      new CopyPlugin({patterns: copyPatterns}),
  ...
}

```

### How Do We Reproduce?
Followed the documentation, added the plugin, also tried to add `array` directly inside the `new CopyPlugin()` declaration, same results.

**Comment by evilebottnawi** [comment]
Please read validation error message and fix it, you don't provide `How Do We Reproduce?`, so I can't help, sorry
