### ISSUE TITLE
Webpack CopyPlugin no longer able to copy fonts from directory after upgrade using Webpack-dev-server

### ISSUE THREAD

**Issue by raptoria** [webpack-contrib/copy-webpack-plugin#527]
- Operating System: Mac OS 10.15.6
- Node Version: v12.14.1
- NPM Version: 6.13.4
- webpack Version: 4.44.1
- copy-webpack-plugin Version: 6.1.0

### Expected Behavior
using CopyPlugin in conjunction with WriteFilePlugin I should be able to serve up my fonts at a specific path, eg. 'fonts' and this should work using webpack-dev-server and in production.

### Actual Behavior

The fonts aren't copied over, so there is a ModuleBuildError because they can't be resolved inside the .scss file. This was working prior to upgrading webpack and copy-webpack-plugin.

### Code

``` 
new CopyPlugin({
      patterns: [
        { from: 'src/assets/fonts', to: 'fonts' },
      ],
    }),
    new WriteFilePlugin()
```

Error:
```
ERROR in ./src/App/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '/fonts/OpenSans-Regular.ttf' in '/Users/raptoria/projects/pnlchart/src/App'
    at /Users/raptoria/projects/pnlchart/node_modules/enhanced-resolve/lib/Resolver.js:209:21
    at /Users/raptoria/projects/pnlchart/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/raptoria/projects/pnlchart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/raptoria/projects/pnlchart/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /Users/raptoria/projects/pnlchart/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/raptoria/projects/pnlchart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/raptoria/projects/pnlchart/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/raptoria/projects/pnlchart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/raptoria/projects/pnlchart/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /Users/raptoria/projects/pnlchart/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/raptoria/projects/pnlchart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/raptoria/projects/pnlchart/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/raptoria/projects/pnlchart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/raptoria/projects/pnlchart/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/raptoria/projects/pnlchart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/raptoria/projects/pnlchart/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at /Users/raptoria/projects/pnlchart/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/raptoria/projects/pnlchart/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/raptoria/projects/pnlchart/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/raptoria/projects/pnlchart/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/Users/raptoria/projects/pnlchart/node_modules/css-loader/dist/index.js:154:5)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
 @ ./src/App/App.tsx 23:0-21
 @ ./src/index.tsx
ℹ ｢wdm｣: Failed to compile.
```

### How Do We Reproduce?

Reproducible Repo:
https://github.com/raptoria/pnlchart

**Comment by evilebottnawi** [comment]
Not related to `copy-webpack-plugin`, you try to resolved assets what doesn't exists (because copy-webpack-plugin emit assets after loaders), do not use copy-webpack-plugin for this case, just put fonts in `fonts` directory and rewrite urls:
```css
a {
  src: url('./fonts/OpenSans-Regular.ttf');
}
```

**Comment by evilebottnawi** [comment]
Also you don't need `WriteFilePlugin` because we have https://webpack.js.org/configuration/dev-server/#devserverwritetodisk- for this case

**Comment by raptoria** [comment]
thanks!
