### ISSUE TITLE
Error: Module.entryModule: Multiple entry modules are not supported by the deprecated API

### ISSUE THREAD

**Issue by vsylvestre** [webpack-contrib/copy-webpack-plugin#561]
- Operating System: Windows 10
- Node Version: 12.13.0
- NPM Version: 6.14.5
- webpack Version: 5.9.0
- copy-webpack-plugin Version: 6.3.2

### Expected Behavior

The latest version of copy-webpack-plugin should work with webpack 5.

### Actual Behavior

After migrating to webpack 5, there's a build error that seems to come from copy-webpack-plugin.

### Code

https://gist.github.com/vsylvestre/acfb1efde597a7affd3ad1a3ac4efe25

### How Do We Reproduce?

- We upgraded all of our webpack plugins to the latest available version (including copy-webpack-plugin)
- We then updated webpack from version 4 to version 5
- The build failed, with the following error:

```
HookWebpackError: Module.entryModule: Multiple entry modules are not supported by the deprecated API (Use the new ChunkGroup API)
    at makeWebpackError (C:\work\schematic-editor\src\client\schematic-editor\node_modules\webpack\lib\HookWebpackError.js:49:9)
    at C:\work\schematic-editor\src\client\schematic-editor\node_modules\webpack\lib\Compilation.js:2107:11
    at eval (eval at create (C:\work\schematic-editor\src\client\schematic-editor\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:33:1)
    at fn (C:\work\schematic-editor\src\client\schematic-editor\node_modules\webpack\lib\Compilation.js:334:17)
    at _next0 (eval at create (C:\work\schematic-editor\src\client\schematic-editor\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:31:1)
    at eval (eval at create (C:\work\schematic-editor\src\client\schematic-editor\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:44:1)
    at eval (eval at create (C:\work\schematic-editor\src\client\schematic-editor\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at C:\work\schematic-editor\src\client\schematic-editor\node_modules\webpack\lib\Compilation.js:355:10
    at Hook.eval [as callAsync] (eval at create (C:\work\schematic-editor\src\client\schematic-editor\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\work\schematic-editor\src\client\schematic-editor\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at C:\work\schematic-editor\src\client\schematic-editor\node_modules\webpack\lib\Compilation.js:367:46
    at C:\work\schematic-editor\src\client\schematic-editor\node_modules\copy-webpack-plugin\dist\index.js:588:9
```

As we can see from the last line, it seems like this originates from copy-webpack-plugin. Let me know if it's actually something from our webpack config that generates this.

**Comment by alexander-akait** [comment]
Please provide reproducible test repo

**Comment by alexander-akait** [comment]
we don't use `Module.entryModule`

**Comment by alexander-akait** [comment]
Maybe bug on `fork-ts-checker-webpack-plugin` plugin (they fixed many of them in near future), anyway here is plugin is not compatibility with weback@5 (according deprecation message), unfortunately I can't help without more information (I don't know your plugins/loaders version and code), anyway feel free to feedback or provide minimum reproducible test repo and I will help
