### ISSUE TITLE
Version 10 doesn't work with yarn berry pnp module resolution

### ISSUE THREAD

**Issue by jackw** [webpack-contrib/copy-webpack-plugin#643]
### Actual Behavior

Upgrading copy-webpack-plugin from v9 to v10 in a repo that uses yarn's pnp module resolution results in failing builds due to not being able to find `globby`. Below is the error in terminal:

```shell
yarn build 
[webpack-cli] HookWebpackError: Cannot find package 'globby' imported from /Users/jackwestbrook/Sandbox/repo-copy-webpack-plugin-pnp/.yarn/__virtual__/copy-webpack-plugin-virtual-1a86820edc/0/cache/copy-webpack-plugin-npm-10.0.0-cbf3ed64fd-70652af613.zip/node_modules/copy-webpack-plugin/dist/index.js
Did you mean to import globby-npm-12.0.2-6be2a4aac6-f474ced866.zip/node_modules/globby/index.js?
    at makeWebpackError (/Users/jackwestbrook/Sandbox/repo-copy-webpack-plugin-pnp/.yarn/__virtual__/webpack-virtual-6c5f2d62d7/0/cache/webpack-npm-5.64.1-77fbd9ac18-d2a1baddae.zip/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/jackwestbrook/Sandbox/repo-copy-webpack-plugin-pnp/.yarn/__virtual__/webpack-virtual-6c5f2d62d7/0/cache/webpack-npm-5.64.1-77fbd9ac18-d2a1baddae.zip/node_modules/webpack/lib/Compilation.js:3055:12
    at eval (eval at create (/Users/jackwestbrook/Sandbox/repo-copy-webpack-plugin-pnp/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:51:1)
    at /Users/jackwestbrook/Sandbox/repo-copy-webpack-plugin-pnp/.yarn/__virtual__/webpack-virtual-6c5f2d62d7/0/cache/webpack-npm-5.64.1-77fbd9ac18-d2a1baddae.zip/node_modules/webpack/lib/Compilation.js:508:26
    at /Users/jackwestbrook/Sandbox/repo-copy-webpack-plugin-pnp/.yarn/__virtual__/copy-webpack-plugin-virtual-1a86820edc/0/cache/copy-webpack-plugin-npm-10.0.0-cbf3ed64fd-70652af613.zip/node_modules/copy-webpack-plugin/dist/index.js:485:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'globby' imported from /Users/jackwestbrook/Sandbox/repo-copy-webpack-plugin-pnp/.yarn/__virtual__/copy-webpack-plugin-virtual-1a86820edc/0/cache/copy-webpack-plugin-npm-10.0.0-cbf3ed64fd-70652af613.zip/node_modules/copy-webpack-plugin/dist/index.js
Did you mean to import globby-npm-12.0.2-6be2a4aac6-f474ced866.zip/node_modules/globby/index.js?
    at new NodeError (node:internal/errors:371:5)
    at packageResolve (node:internal/modules/esm/resolve:884:9)
    at moduleResolve (node:internal/modules/esm/resolve:929:18)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ESMLoader.import (node:internal/modules/esm/loader:276:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1041:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:21)
    at importModuleDynamically (node:vm:381:46)
caused by plugins in Compilation.hooks.processAssets
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'globby' imported from /Users/jackwestbrook/Sandbox/repo-copy-webpack-plugin-pnp/.yarn/__virtual__/copy-webpack-plugin-virtual-1a86820edc/0/cache/copy-webpack-plugin-npm-10.0.0-cbf3ed64fd-70652af613.zip/node_modules/copy-webpack-plugin/dist/index.js
Did you mean to import globby-npm-12.0.2-6be2a4aac6-f474ced866.zip/node_modules/globby/index.js?
    at new NodeError (node:internal/errors:371:5)
    at packageResolve (node:internal/modules/esm/resolve:884:9)
    at moduleResolve (node:internal/modules/esm/resolve:929:18)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ESMLoader.import (node:internal/modules/esm/loader:276:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1041:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:21)
    at importModuleDynamically (node:vm:381:46)

```

### Expected Behavior

For the webpack build to complete and the files to be copied to their destination

### How Do We Reproduce?

I've put a repo together with a minimal reproduction at https://github.com/jackw/repo-copy-webpack-plugin-pnp

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
System:
    OS: macOS 11.6.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 55.89 MB / 16.00 GB
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 3.1.0 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Brave Browser: 96.1.32.106
    Chrome: 96.0.4664.55
    Chrome Canary: 86.0.4239.0
    Firefox: 94.0.1
    Firefox Nightly: 81.0a1
    Safari: 15.1
    Safari Technology Preview: 15.4
  Monorepos:
    Yarn Workspaces: 3.1.0
```

**Comment by jackw** [comment]
Ah I see. Thanks so much for the quick response. Will follow up in the yarn repo. 👍

**Comment by alexander-akait** [comment]
Unfortunately we can't return `require`, because `globby` is ESM now, anyway it works with npm, so I think something wrong on yarn side

**Comment by magnattic** [comment]
@jackw Did you find a solution for this?

**Comment by AllanChain** [comment]
@magnattic See https://github.com/facebook/docusaurus/pull/6350#issuecomment-1013214763 . You need to set yarn version to canary (3.2)
