### ISSUE TITLE
CopyWebpackPlugin 10.1 gives "Invalid host defined options"

### ISSUE THREAD

**Issue by mattgodbolt** [webpack-contrib/copy-webpack-plugin#653]
### Bug report

When upgrading to v10.1 I statrted getting `HookWebpackError: Invalid host defined options` on any trivial usage of CopyWebpackPlugin.

It seems others see it too, and the advice is "don't upgrade to v10" - https://stackoverflow.com/questions/70080671/copy-webpack-plugin-error-invalid-host-defined-options

### Actual Behavior

Updating to v10 and running a webpack operation on my source tree gives:

```
$ npm run start

> compiler-explorer@0.0.3 start /home/matthew/dev/ce/compiler-explorer
> webpack && cross-env NODE_ENV=LOCAL node -r esm app.js

[webpack-cli] HookWebpackError: Invalid host defined options
    at makeWebpackError (/home/matthew/dev/ce/compiler-explorer/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /home/matthew/dev/ce/compiler-explorer/node_modules/webpack/lib/Compilation.js:3055:12
    at eval (eval at create (/home/matthew/dev/ce/compiler-explorer/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:52:1)
    at /home/matthew/dev/ce/compiler-explorer/node_modules/webpack/lib/Compilation.js:508:26
    at /home/matthew/dev/ce/compiler-explorer/node_modules/copy-webpack-plugin/dist/index.js:713:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
-- inner error --
TypeError: Invalid host defined options
    at /home/matthew/dev/ce/compiler-explorer/node_modules/copy-webpack-plugin/dist/index.js:709:13
    at fn (/home/matthew/dev/ce/compiler-explorer/node_modules/webpack/lib/Compilation.js:507:9)
    at Hook.eval [as callAsync] (eval at create (/home/matthew/dev/ce/compiler-explorer/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:50:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/matthew/dev/ce/compiler-explorer/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/home/matthew/dev/ce/compiler-explorer/node_modules/webpack/lib/Compilation.js:3052:34)
    at /home/matthew/dev/ce/compiler-explorer/node_modules/webpack/lib/Compilation.js:3100:10
    at symbolIterator (/home/matthew/dev/ce/compiler-explorer/node_modules/neo-async/async.js:3485:9)
    at timesSync (/home/matthew/dev/ce/compiler-explorer/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/home/matthew/dev/ce/compiler-explorer/node_modules/neo-async/async.js:3463:5)
    at Compilation.createChunkAssets (/home/matthew/dev/ce/compiler-explorer/node_modules/webpack/lib/Compilation.js:4452:12)
caused by plugins in Compilation.hooks.processAssets
TypeError: Invalid host defined options
    at /home/matthew/dev/ce/compiler-explorer/node_modules/copy-webpack-plugin/dist/index.js:709:13
    at fn (/home/matthew/dev/ce/compiler-explorer/node_modules/webpack/lib/Compilation.js:507:9)
    at Hook.eval [as callAsync] (eval at create (/home/matthew/dev/ce/compiler-explorer/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:50:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/matthew/dev/ce/compiler-explorer/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/home/matthew/dev/ce/compiler-explorer/node_modules/webpack/lib/Compilation.js:3052:34)
    at /home/matthew/dev/ce/compiler-explorer/node_modules/webpack/lib/Compilation.js:3100:10
    at symbolIterator (/home/matthew/dev/ce/compiler-explorer/node_modules/neo-async/async.js:3485:9)
    at timesSync (/home/matthew/dev/ce/compiler-explorer/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/home/matthew/dev/ce/compiler-explorer/node_modules/neo-async/async.js:3463:5)
    at Compilation.createChunkAssets (/home/matthew/dev/ce/compiler-explorer/node_modules/webpack/lib/Compilation.js:4452:12)
```

The line referenced in copy-webpack-plugin is trying to `require` `globby` (which I noticed went to v12 in this release). `globby` v12.2 is installed (looking inside my `node_modules`).

### Expected Behavior

Webpack should not throw this error iniitalising/executing the copy plugin.

### How Do We Reproduce?

clone https://github.com/compiler-explorer/compiler-explorer/tree/mg/webpack5-cwp-issue and then `npm install; npm run start`

**Comment by alexander-akait** [comment]
It means your env is not supported `import(...)`, related https://github.com/webpack-contrib/copy-webpack-plugin/issues/652, https://github.com/webpack-contrib/copy-webpack-plugin/issues/648, https://github.com/webpack-contrib/copy-webpack-plugin/issues/646 and more, sorry, I can't fix ESM compatibility in other tools like yarn/esm/etc, time to move on ESM

**Comment by alexander-akait** [comment]
https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/index.js#L799

**Comment by alexander-akait** [comment]
What is `webpack-cli` version?

**Comment by mattgodbolt** [comment]
Apologies for not posting this before:

```
$ npx webpack-cli info

  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 547.37 MB / 15.51 GB
  Binaries:
    Node: 14.18.0 - /opt/compiler-explorer/node/bin/node
    npm: 6.14.15 - /opt/compiler-explorer/node/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0
  Packages:
    copy-webpack-plugin: ^10.1.0 => 10.1.0 
    css-loader: ^6.5.1 => 6.5.1 
    file-loader: ^6.2.0 => 6.2.0 
    html-loader: ^0.5.5 => 0.5.5 
    monaco-editor-webpack-plugin: ^4.2.0 => 4.2.0 
    optimize-css-assets-webpack-plugin: ^5.0.8 => 5.0.8 
    sass-loader: ^12.4.0 => 12.4.0 
    source-map-loader: ^3.0.0 => 3.0.0 
    terser-webpack-plugin: ^5.2.5 => 5.2.5 
    ts-loader: ^9.2.6 => 9.2.6 
    url-loader: ^4.1.1 => 4.1.1 
    webpack: ^5.65.0 => 5.65.0 
    webpack-cli: ^4.9.1 => 4.9.1 
    webpack-dev-middleware: ^5.2.2 => 5.2.2 
    webpack-dev-server: ^4.6.0 => 4.6.0 
    webpack-manifest-plugin: ^4.0.2 => 4.0.2 
```

**Comment by alexander-akait** [comment]
Thanks, you see `TypeError: Invalid host defined options`, because somebody register loader for Node.js (I see `esm` package) and do not implement valid dynamic linker - https://nodejs.org/api/vm.html, look at `importModuleDynamically`, so your host doesn't handle import properly, you can look at our source code and make sure that there is nothing special

**Comment by alexander-akait** [comment]
Another problem can be in https://github.com/zertosh/v8-compile-cache#readme, when package override Node.js module logic and do it wrong

**Comment by alexander-akait** [comment]
Yep, bug in `esm` package, my recommendation - remove it. Rename `webpack.config.esm.js` to `webpack.config.mjs` and do not use `esm`, it will be even faster

**Comment by alexander-akait** [comment]
Also speed up your build by setting:
```
cache: {
        type: "filesystem",
    },
```

**Comment by mattgodbolt** [comment]
Thanks @alexander-akait .

**Comment by alexander-akait** [comment]
Feel free to feedback, nothing to fix on our side, ESM still has bad support in many cases, it is bad, hope it will be fixed in near future

**Comment by amakhrov** [comment]
> nothing to fix on our side

Perhaps it's worth mentioning in CHANGELOG? It definitely sounds like a breaking change for many users.

@alexander-akait

**Comment by sushidesu** [comment]
In my case, I encountered the same error when using `copy-webpack-plugin@10.0.0` with `webpack-cli@4.9.0`.

If the version of `copy-webpack-plugin` is newer than `10.0.0`, there was no detailed error message, only `Segmentation fault (core dumped)`.

```sh
$ yarn webpack
yarn run v1.22.17
$ /home/sushidesu/dev/test/copywebpack-test/node_modules/.bin/webpack
Segmentation fault (core dumped)
error Command failed with exit code 139.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I upgraded `webpack-cli@4.9.0` to `v4.9.1` and it now works.

**Comment by alexander-akait** [comment]
@sushidesu Yes, update webpack-cli firstly, we fixed some ESM issues

@amakhrov I do major release for this changes, unfortunately I can't describe all possible problems with ESM, a lot of tools still have bad ESM supporting, some of them just can be removed, some of them require fixes on their side. In fact, it’s even good that you are faced with such problems. It means we will do ESM supporting better.
