### ISSUE TITLE
HookWebpackError: Unexpected token '??='

### ISSUE THREAD

**Issue by joetidee** [webpack-contrib/copy-webpack-plugin#772]
### Actual Behaviour

I'm getting this error in the terminal when running my application:
```
[webpack-cli] HookWebpackError: Unexpected token '??='
    at makeWebpackError (/Users/joe/Sources/tidee-life/packages/tidee-life-web/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/joe/Sources/tidee-life/packages/tidee-life-web/node_modules/webpack/lib/Compilation.js:3175:12
    at eval (eval at create (/Users/joe/Sources/tidee-life/packages/tidee-life-web/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at /Users/joe/Sources/tidee-life/packages/tidee-life-web/node_modules/webpack/lib/Compilation.js:518:26
    at /Users/joe/Sources/tidee-life/packages/tidee-life-web/node_modules/copy-webpack-plugin/dist/index.js:632:13
-- inner error --
SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
caused by plugins in Compilation.hooks.processAssets
SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
```

### Expected Behavior

I should not see any errors.

### How Do We Reproduce?
Node 14.19.1
Webpack 5.91.0
copy-webpack-plugin 12.0.2

Code inside webpack.config.js file:
```
new CopyWebpackPlugin({
        patterns: [
            { from: 'src/assets', to: 'assets' }
        ]
    }),
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 642.74 MB / 8.00 GB
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    npm: 7.6.0 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Chrome: 123.0.6312.87
    Safari: 14.1.2
  Monorepos:
    Lerna: 4.0.0
  Packages:
    webpack-bundle-analyzer: ^3.6.0 => 3.6.0

**Comment by joetidee** [comment]
Fixed by upgrading node to v18
